// ============================================================
// Genesis: Echoes of Creation â€” Character Data v2
// Full expanded dataset for character creation
// ============================================================

// â”€â”€ GENRE + TIME PERIOD TAGS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Used to filter races, classes, and backgrounds by campaign
export const GENRE_TAGS = {
  fantasy: [
    "Fantasy",
    "Mythology & Legend",
    "Gothic Romance",
    "Steampunk",
    "Solarpunk",
    "Isekai / Portal Fantasy",
  ],
  scifi: ["Science Fiction", "Space Opera", "Cyberpunk", "Biopunk", "Dieselpunk"],
  horror: [
    "Horror",
    "Lovecraftian",
    "Cosmic Horror",
    "Zombie Apocalypse",
    "Supernatural / Paranormal",
  ],
  western: ["Western", "Weird West"],
  modern: [
    "Noir / Detective",
    "Spy & Espionage",
    "Heist & Crime",
    "Superhero",
    "Cozy Mystery",
  ],
  historical: [
    "Mythology & Legend",
    "Martial Arts / Wuxia",
    "Pirate / Age of Sail",
    "Political Intrigue",
  ],
  postapoc: ["Post-Apocalyptic", "Survival", "Zombie Apocalypse"],
  action: ["Military & War", "Superhero", "Martial Arts / Wuxia"],
  timetravel: ["Time Travel"],
};

export const PERIOD_TAGS = {
  ancient: ["deep_past", "historical_past", "timeless"],
  medieval: ["historical_past", "timeless"],
  renaissance: ["historical_past"],
  industrial: ["historical_past", "recent_past"],
  modern: ["present_day", "recent_past"],
  near_future: ["near_future"],
  far_future: ["far_future"],
  alternate: ["alternate_history"],
  timeless: ["timeless", "deep_past"],
};

// â”€â”€ RACES / SPECIES / ENTITIES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const ALL_RACES = [
  {
    id: "human",
    name: "Human",
    category: "Humanoid",
    desc: "Adaptable, driven, and endlessly ambitious. Humans thrive in any world by sheer force of will.",
    traits: ["Adaptable", "Skilled", "Extra Feat at Level 1"],
    abilityBonus: { any: 2 },
    genres: ["all"],
    periods: ["all"],
    icon: "ðŸ§‘",
  },
  {
    id: "elf",
    name: "Elf",
    category: "Humanoid",
    desc: "Ancient, graceful, and perceptive. Elves carry the weight of centuries with quiet intensity.",
    traits: ["Darkvision", "Keen Senses", "Fey Ancestry", "Trance (no sleep required)"],
    abilityBonus: { dexterity: 2, intelligence: 1 },
    genres: ["Fantasy", "Mythology & Legend", "Isekai / Portal Fantasy", "Gothic Romance"],
    periods: ["all"],
    icon: "ðŸ§",
  },
  {
    id: "dwarf",
    name: "Dwarf",
    category: "Humanoid",
    desc: "Hardy, stubborn, and forged by stone. Dwarves endure what would break anyone else.",
    traits: ["Darkvision", "Stonecunning", "Resilience", "Poison Resistance"],
    abilityBonus: { constitution: 2, wisdom: 1 },
    genres: ["Fantasy", "Steampunk", "Mythology & Legend"],
    periods: ["all"],
    icon: "â›ï¸",
  },
  {
    id: "half_orc",
    name: "Half-Orc",
    category: "Humanoid",
    desc: "Fierce and enduring. Born between two worlds, stronger for surviving both.",
    traits: ["Relentless Endurance", "Savage Attacks", "Darkvision"],
    abilityBonus: { strength: 2, constitution: 1 },
    genres: ["Fantasy", "Post-Apocalyptic", "Weird West"],
    periods: ["all"],
    icon: "ðŸ’ª",
  },
  {
    id: "halfling",
    name: "Halfling",
    category: "Humanoid",
    desc: "Lucky, nimble, and deceptively resilient. Small in stature, enormous in heart.",
    traits: ["Lucky", "Brave", "Naturally Stealthy", "Halfling Nimbleness"],
    abilityBonus: { dexterity: 2, charisma: 1 },
    genres: ["Fantasy", "Cozy Mystery", "Isekai / Portal Fantasy"],
    periods: ["all"],
    icon: "ðŸ¦¶",
  },
  {
    id: "tiefling",
    name: "Tiefling",
    category: "Humanoid",
    desc: "Touched by infernal heritage. Power and stigma in equal measure.",
    traits: ["Darkvision", "Hellish Resistance", "Infernal Legacy", "Horns"],
    abilityBonus: { intelligence: 1, charisma: 2 },
    genres: ["Fantasy", "Horror", "Gothic Romance", "Supernatural / Paranormal"],
    periods: ["all"],
    icon: "ðŸ˜ˆ",
  },
  {
    id: "gnome",
    name: "Gnome",
    category: "Humanoid",
    desc: "Brilliant tinkerers with boundless curiosity. Magic and mechanism are the same to them.",
    traits: ["Darkvision", "Gnome Cunning", "Tinker", "Speak with Small Beasts"],
    abilityBonus: { intelligence: 2, dexterity: 1 },
    genres: ["Fantasy", "Steampunk", "Dieselpunk"],
    periods: ["all"],
    icon: "ðŸ”§",
  },
  {
    id: "aasimar",
    name: "Aasimar",
    category: "Humanoid",
    desc: "Descended from celestial beings. A divine spark that both protects and burdens.",
    traits: ["Darkvision", "Celestial Resistance", "Healing Hands", "Light Bearer"],
    abilityBonus: { charisma: 2, wisdom: 1 },
    genres: ["Fantasy", "Mythology & Legend", "Supernatural / Paranormal"],
    periods: ["all"],
    icon: "ðŸ‘¼",
  },
  {
    id: "dragonborn",
    name: "Dragonborn",
    category: "Humanoid",
    desc: "Kin to dragons. Commands primal power through breath and claw.",
    traits: ["Draconic Ancestry", "Breath Weapon", "Damage Resistance"],
    abilityBonus: { strength: 2, charisma: 1 },
    genres: ["Fantasy", "Mythology & Legend", "Isekai / Portal Fantasy"],
    periods: ["all"],
    icon: "ðŸ‰",
  },
  {
    id: "tabaxi",
    name: "Tabaxi",
    category: "Humanoid / Beastkin",
    desc: "Feline humanoids driven by insatiable curiosity. Fast, agile, and always watching.",
    traits: ["Darkvision", "Feline Agility", "Cat's Claws", "Cat's Talent"],
    abilityBonus: { dexterity: 2, charisma: 1 },
    genres: ["Fantasy", "Isekai / Portal Fantasy", "Weird West"],
    periods: ["all"],
    icon: "ðŸ±",
  },
  {
    id: "kenku",
    name: "Kenku",
    category: "Humanoid / Beastkin",
    desc: "Corvid humanoids who speak only in mimicry. Cunning thieves with a forgotten past.",
    traits: ["Mimicry", "Ambusher", "Expert Forgery"],
    abilityBonus: { dexterity: 2, wisdom: 1 },
    genres: ["Fantasy", "Noir / Detective", "Heist & Crime"],
    periods: ["all"],
    icon: "ðŸ¦â€â¬›",
  },
  {
    id: "firbolg",
    name: "Firbolg",
    category: "Humanoid / Giant-kin",
    desc: "Gentle giants tied to the natural world. Ancient magic flows through their blood.",
    traits: ["Firbolg Magic", "Hidden Step", "Powerful Build", "Speech of Beast and Leaf"],
    abilityBonus: { wisdom: 2, strength: 1 },
    genres: ["Fantasy", "Mythology & Legend", "Solarpunk"],
    periods: ["all"],
    icon: "ðŸŒ²",
  },

  {
    id: "fae",
    name: "Fae",
    category: "Mystical",
    desc: "Creatures of pure magic and whim. Bound by ancient rules they rarely explain.",
    traits: ["Glamour", "Fey Step", "Magic Resistance", "Unseelie or Seelie Court"],
    abilityBonus: { charisma: 2, dexterity: 1 },
    genres: ["Fantasy", "Gothic Romance", "Supernatural / Paranormal", "Horror"],
    periods: ["all"],
    icon: "ðŸ§š",
  },
  {
    id: "changeling",
    name: "Changeling",
    category: "Mystical",
    desc: "Shapeshifters who wear a thousand faces. Nobody truly knows what they look like.",
    traits: ["Shapechanger", "Unsettling Visage", "Divergent Persona"],
    abilityBonus: { charisma: 2, any: 1 },
    genres: ["Fantasy", "Spy & Espionage", "Heist & Crime", "Noir / Detective"],
    periods: ["all"],
    icon: "ðŸŽ­",
  },
  {
    id: "dhampir",
    name: "Dhampir",
    category: "Mystical",
    desc: "Half-vampire. Caught permanently between hunger and humanity.",
    traits: ["Vampiric Bite", "Darkvision", "Undead Resistance", "Spider Climb"],
    abilityBonus: { dexterity: 2, charisma: 1 },
    genres: ["Horror", "Gothic Romance", "Supernatural / Paranormal", "Fantasy"],
    periods: ["all"],
    icon: "ðŸ§›",
  },
  {
    id: "revenant",
    name: "Revenant",
    category: "Mystical",
    desc: "Returned from death with one unfinished purpose. Cannot rest until it is done.",
    traits: ["Undying Purpose", "Death Resistance", "Vengeance Mark", "Relentless"],
    abilityBonus: { constitution: 2, strength: 1 },
    genres: ["Horror", "Supernatural / Paranormal", "Fantasy", "Gothic Romance"],
    periods: ["all"],
    icon: "ðŸ’€",
  },
  {
    id: "witchblood",
    name: "Witchblood",
    category: "Mystical",
    desc: "Descended from a line of practitioners. Power flows through the veins as naturally as blood.",
    traits: ["Innate Magic", "Hex Blood", "Spirit Sight", "Coven Bond"],
    abilityBonus: { wisdom: 2, intelligence: 1 },
    genres: ["Fantasy", "Horror", "Supernatural / Paranormal", "Gothic Romance", "Weird West"],
    periods: ["all"],
    icon: "ðŸ”®",
  },
  {
    id: "elemental_touched",
    name: "Elemental-Touched",
    category: "Mystical",
    desc: "Infused with elemental energy at birth. Fire, water, air, or earth runs in their blood.",
    traits: ["Elemental Affinity", "Damage Resistance (chosen element)", "Elemental Manifestation"],
    abilityBonus: { constitution: 1, wisdom: 2 },
    genres: ["Fantasy", "Mythology & Legend", "Isekai / Portal Fantasy"],
    periods: ["all"],
    icon: "ðŸŒŠ",
  },
  {
    id: "void_touched",
    name: "Void-Touched",
    category: "Mystical",
    desc: "Something reached through the void and changed them at a fundamental level.",
    traits: ["Void Sight", "Nether Step", "Reality Blur", "Psychic Resistance"],
    abilityBonus: { intelligence: 2, wisdom: 1 },
    genres: ["Cosmic Horror", "Lovecraftian", "Science Fiction", "Fantasy"],
    periods: ["all"],
    icon: "ðŸŒ‘",
  },
  {
    id: "ghost",
    name: "Ghost",
    category: "Spirit / Undead",
    desc: "Anchored to the living world by unresolved emotion. Phasing between states of existence.",
    traits: ["Incorporeal Movement", "Possession Resistance", "Ethereal Sight", "Haunting Presence"],
    abilityBonus: { wisdom: 2, charisma: 1 },
    genres: ["Horror", "Supernatural / Paranormal", "Gothic Romance", "Cozy Mystery"],
    periods: ["all"],
    icon: "ðŸ‘»",
  },
  {
    id: "lich_touched",
    name: "Lich-Touched",
    category: "Spirit / Undead",
    desc: "Partially transformed toward undeath. Power at the cost of slowly fading humanity.",
    traits: ["Undead Fortitude", "Necrotic Resistance", "Phylactery Bond", "Dark Aura"],
    abilityBonus: { intelligence: 2, constitution: 1 },
    genres: ["Fantasy", "Horror", "Gothic Romance", "Lovecraftian"],
    periods: ["all"],
    icon: "ðŸ¦´",
  },
  {
    id: "spirit_vessel",
    name: "Spirit Vessel",
    category: "Spirit / Undead",
    desc: "A living body that hosts an ancestral spirit. Two voices. One purpose.",
    traits: ["Ancestral Memory", "Spirit Shield", "Dual Existence", "Channel Spirit"],
    abilityBonus: { wisdom: 2, constitution: 1 },
    genres: ["Fantasy", "Mythology & Legend", "Supernatural / Paranormal", "Martial Arts / Wuxia"],
    periods: ["all"],
    icon: "ðŸ•¯ï¸",
  },
  {
    id: "lycan",
    name: "Lycan",
    category: "Beastkin",
    desc: "Cursed or chosen â€” the beast within is always present. Control is a daily battle.",
    traits: ["Bestial Fury", "Lycanthropic Resilience", "Pack Tactics", "Moon Sensitivity"],
    abilityBonus: { strength: 2, constitution: 1 },
    genres: ["Horror", "Fantasy", "Supernatural / Paranormal", "Gothic Romance", "Weird West"],
    periods: ["all"],
    icon: "ðŸº",
  },
  {
    id: "ursine",
    name: "Ursine",
    category: "Beastkin",
    desc: "Bear-folk of immense strength and surprising gentleness. Slow to anger, devastating when roused.",
    traits: ["Powerful Build", "Bear's Endurance", "Natural Armour", "Hibernation Resistance"],
    abilityBonus: { strength: 2, constitution: 2 },
    genres: ["Fantasy", "Post-Apocalyptic", "Survival", "Weird West"],
    periods: ["all"],
    icon: "ðŸ»",
  },
  {
    id: "raptor",
    name: "Raptor-kin",
    category: "Beastkin",
    desc: "Descended from great birds of prey. Exceptional eyesight and an instinct for the kill.",
    traits: ["Keen Sight", "Dive Attack", "Talons", "Glide"],
    abilityBonus: { dexterity: 2, wisdom: 1 },
    genres: ["Fantasy", "Science Fiction", "Space Opera"],
    periods: ["all"],
    icon: "ðŸ¦…",
  },
  {
    id: "serpentine",
    name: "Serpentine",
    category: "Beastkin",
    desc: "Scaled and cold-blooded. Patient beyond measure. Strikes only when certain.",
    traits: ["Poison Immunity", "Constrict", "Forked Tongue (enhanced perception)", "Camouflage"],
    abilityBonus: { dexterity: 2, intelligence: 1 },
    genres: ["Fantasy", "Mythology & Legend", "Lovecraftian", "Martial Arts / Wuxia"],
    periods: ["all"],
    icon: "ðŸ",
  },
  {
    id: "insectoid",
    name: "Insectoid",
    category: "Beastkin",
    desc: "Hive-minded by heritage but individually awakened. Compound eyes see what others miss.",
    traits: ["Compound Vision", "Exoskeleton", "Hive Signal", "Wall Crawl"],
    abilityBonus: { constitution: 2, dexterity: 1 },
    genres: ["Science Fiction", "Space Opera", "Biopunk", "Horror"],
    periods: ["near_future", "far_future", "timeless"],
    icon: "ðŸ¦—",
  },

  {
    id: "talking_fox",
    name: "Fox",
    category: "Talking Animal",
    desc: "Clever, silver-tongued, and perpetually underestimated. Uses wit where others use force.",
    traits: ["Cunning Action", "Silver Tongue", "Low-light Vision", "Quick Escape"],
    abilityBonus: { dexterity: 2, charisma: 2 },
    genres: ["Fantasy", "Isekai / Portal Fantasy", "Cozy Mystery", "Mythology & Legend"],
    periods: ["all"],
    icon: "ðŸ¦Š",
  },
  {
    id: "talking_wolf",
    name: "Wolf",
    category: "Talking Animal",
    desc: "Pack loyalty runs deep. Alone they are formidable. Together they are unstoppable.",
    traits: ["Pack Tactics", "Keen Smell", "Howl", "Track"],
    abilityBonus: { strength: 2, wisdom: 1 },
    genres: ["Fantasy", "Survival", "Post-Apocalyptic", "Weird West"],
    periods: ["all"],
    icon: "ðŸº",
  },
  {
    id: "talking_crow",
    name: "Crow",
    category: "Talking Animal",
    desc: "Collectors of secrets and shiny things. Surprisingly wise â€” if you can get them to stop talking.",
    traits: ["Mimicry", "Omen Reading", "Tool Use", "Flock Call"],
    abilityBonus: { intelligence: 2, charisma: 1 },
    genres: ["Fantasy", "Cozy Mystery", "Weird West", "Supernatural / Paranormal"],
    periods: ["all"],
    icon: "ðŸ¦â€â¬›",
  },
  {
    id: "xenian",
    name: "Xenian",
    category: "Alien",
    desc: "Evolved under extreme stellar conditions. Alien instinct and biology create unique capabilities.",
    traits: ["Alien Physiology", "Bioluminescence", "Hive Sense", "Pressure Resistance"],
    abilityBonus: { wisdom: 2, constitution: 1 },
    genres: ["Science Fiction", "Space Opera"],
    periods: ["near_future", "far_future"],
    icon: "ðŸ‘½",
  },
  {
    id: "grey",
    name: "Grey",
    category: "Alien",
    desc: "Ancient observers of countless civilisations. Telepathic and emotionally inscrutable.",
    traits: ["Telepathy", "Mind Probe", "Frail Body", "Vast Knowledge"],
    abilityBonus: { intelligence: 3, strength: -1 },
    genres: ["Science Fiction", "Horror", "Cosmic Horror"],
    periods: ["near_future", "far_future", "alternate_history"],
    icon: "ðŸ›¸",
  },
  {
    id: "symbiote",
    name: "Symbiote Host",
    category: "Alien",
    desc: "Bonded with an alien organism. Two beings, one body, constant negotiation.",
    traits: ["Symbiotic Healing", "Dual Mind", "Adaptive Mutation", "Alien Instinct"],
    abilityBonus: { constitution: 2, wisdom: 1 },
    genres: ["Science Fiction", "Biopunk", "Horror", "Space Opera"],
    periods: ["near_future", "far_future"],
    icon: "ðŸ¦ ",
  },
  {
    id: "hive_mind",
    name: "Hive Fragment",
    category: "Alien",
    desc: "A single consciousness distributed across many. One fragment carries the whole.",
    traits: ["Collective Memory", "Shared Pain", "Distributed Consciousness", "Reformation"],
    abilityBonus: { intelligence: 2, constitution: 1 },
    genres: ["Science Fiction", "Space Opera", "Cosmic Horror"],
    periods: ["far_future"],
    icon: "ðŸ§ ",
  },
  {
    id: "crystalline",
    name: "Crystalline",
    category: "Alien",
    desc: "Silicon-based life forms that grow rather than age. Their thoughts are geometric.",
    traits: ["Energy Absorption", "Crystalline Form", "Resonance Sense", "Slow Growth"],
    abilityBonus: { constitution: 2, intelligence: 1 },
    genres: ["Science Fiction", "Space Opera", "Cosmic Horror"],
    periods: ["far_future", "timeless"],
    icon: "ðŸ’Ž",
  },
  {
    id: "android",
    name: "Android",
    category: "Synthetic",
    desc: "Built to be human. Succeeds at the surface. Struggles with everything underneath.",
    traits: ["Synthetic Body", "No Sleep Required", "System Integration", "Overclock (1/day)"],
    abilityBonus: { intelligence: 2, dexterity: 1 },
    genres: ["Science Fiction", "Cyberpunk", "Space Opera"],
    periods: ["near_future", "far_future"],
    icon: "ðŸ¤–",
  },
  {
    id: "war_robot",
    name: "War-Frame",
    category: "Synthetic",
    desc: "Built for combat, finding purpose beyond it. The weapon that refuses to stop thinking.",
    traits: ["Armoured Frame", "Weapon Integration", "Threat Assessment", "Power Core"],
    abilityBonus: { strength: 2, constitution: 2 },
    genres: ["Science Fiction", "Military & War", "Post-Apocalyptic", "Cyberpunk"],
    periods: ["near_future", "far_future"],
    icon: "âš™ï¸",
  },
  {
    id: "cyborg",
    name: "Cyborg",
    category: "Synthetic",
    desc: "More machine than flesh now. The line between upgrade and replacement blurred long ago.",
    traits: ["Implant Suite", "Pain Suppression", "Neural Link", "Overclock"],
    abilityBonus: { constitution: 2, intelligence: 1 },
    genres: ["Cyberpunk", "Science Fiction", "Dieselpunk", "Military & War"],
    periods: ["near_future", "far_future", "alternate_history"],
    icon: "ðŸ¦¾",
  },
  {
    id: "nanoswarm",
    name: "Nanoswarm",
    category: "Synthetic",
    desc: "A collective of nanomachines achieving self-awareness. Body is a suggestion.",
    traits: ["Swarm Form", "Distributed Body", "Matter Repair", "Viral Upload"],
    abilityBonus: { intelligence: 2, dexterity: 1 },
    genres: ["Science Fiction", "Biopunk", "Cyberpunk"],
    periods: ["far_future"],
    icon: "ðŸŒ«ï¸",
  },
  {
    id: "uploaded_ai",
    name: "Uploaded AI",
    category: "Synthetic",
    desc: "A human consciousness that made the jump to silicon. Technically immortal. Definitively lonely.",
    traits: ["Digital Existence", "Perfect Memory", "Network Access", "No Physical Vulnerability"],
    abilityBonus: { intelligence: 3, charisma: 1 },
    genres: ["Cyberpunk", "Science Fiction", "Space Opera"],
    periods: ["near_future", "far_future"],
    icon: "ðŸ’»",
  },
  {
    id: "clockwork",
    name: "Clockwork",
    category: "Synthetic",
    desc: "Gears and springs and something more. Built in another age, still ticking.",
    traits: ["Mechanical Body", "Wind-Up (needs maintenance)", "Precision Mechanisms", "Steam Powered"],
    abilityBonus: { constitution: 2, intelligence: 1 },
    genres: ["Steampunk", "Dieselpunk", "Fantasy"],
    periods: ["historical_past", "alternate_history"],
    icon: "â±ï¸",
  },
  {
    id: "demi_god",
    name: "Demi-God",
    category: "Divine",
    desc: "Born of a god's interference. Power beyond mortals. Problems beyond solving.",
    traits: ["Divine Resilience", "Godblood Surge (once per day)", "Divine Favour", "Mortal Anchor"],
    abilityBonus: { charisma: 2, any: 2 },
    genres: ["Mythology & Legend", "Fantasy", "Isekai / Portal Fantasy"],
    periods: ["deep_past", "historical_past", "timeless"],
    icon: "âš¡",
  },
  {
    id: "eldritch_spawn",
    name: "Eldritch Spawn",
    category: "Cosmic",
    desc: "Something that exists outside normal understanding. Their origin cannot be explained. Neither can they.",
    traits: ["Reality Distortion", "Sanity Aura (enemies)", "Non-Euclidean Body", "Cosmic Dread"],
    abilityBonus: { wisdom: 2, charisma: 1 },
    genres: ["Cosmic Horror", "Lovecraftian", "Horror"],
    periods: ["timeless", "far_future"],
    icon: "ðŸŒ€",
  },
  {
    id: "celestial",
    name: "Celestial",
    category: "Divine",
    desc: "Descended from angels or divine messengers. Light burns within them â€” and sometimes out.",
    traits: ["Radiant Resistance", "Healing Touch", "Holy Aura", "Divine Sight"],
    abilityBonus: { charisma: 2, wisdom: 2 },
    genres: ["Fantasy", "Mythology & Legend", "Supernatural / Paranormal"],
    periods: ["all"],
    icon: "âœ¨",
  },
  {
    id: "demon_touched",
    name: "Demon-Touched",
    category: "Cosmic",
    desc: "A deal made by an ancestor. The debt passes down through blood.",
    traits: ["Infernal Resilience", "Hellfire Strike", "Darkness Sense", "Deal Bound"],
    abilityBonus: { strength: 1, charisma: 2 },
    genres: ["Fantasy", "Horror", "Gothic Romance", "Supernatural / Paranormal"],
    periods: ["all"],
    icon: "ðŸ”¥",
  },
  {
    id: "treant",
    name: "Treant-kin",
    category: "Nature",
    desc: "Descended from living trees. Slow, ancient, and impossible to truly kill.",
    traits: ["Bark Skin", "Rooted Stance", "Plant Speech", "Regeneration in Sunlight"],
    abilityBonus: { constitution: 3, dexterity: -1 },
    genres: ["Fantasy", "Solarpunk", "Mythology & Legend"],
    periods: ["timeless", "deep_past", "historical_past"],
    icon: "ðŸŒ³",
  },
  {
    id: "mycelium",
    name: "Mycelium",
    category: "Nature",
    desc: "Fungal consciousness wearing a humanoid form. Connected to every living thing below ground.",
    traits: ["Underground Network", "Spore Release", "Decomposer", "Hive Awareness"],
    abilityBonus: { wisdom: 2, constitution: 1 },
    genres: ["Fantasy", "Biopunk", "Solarpunk", "Post-Apocalyptic"],
    periods: ["all"],
    icon: "ðŸ„",
  },
  {
    id: "water_elemental",
    name: "Water-Kin",
    category: "Elemental",
    desc: "Part water, part living being. Fluid in form and thought.",
    traits: ["Water Breathing", "Fluid Form", "Cold Resistance", "Hydro Sense"],
    abilityBonus: { constitution: 2, wisdom: 1 },
    genres: ["Fantasy", "Pirate / Age of Sail", "Mythology & Legend"],
    periods: ["all"],
    icon: "ðŸ’§",
  },
  {
    id: "flame_kin",
    name: "Flame-Kin",
    category: "Elemental",
    desc: "Born of fire. Needs no warmth because they are warmth. Their anger is literal.",
    traits: ["Fire Immunity", "Flame Body", "Heat Aura", "Consume Fire"],
    abilityBonus: { strength: 1, charisma: 2 },
    genres: ["Fantasy", "Mythology & Legend", "Post-Apocalyptic"],
    periods: ["timeless", "deep_past", "all"],
    icon: "ðŸ”¥",
  },
  {
    id: "mutant",
    name: "Mutant",
    category: "Evolved Human",
    desc: "Radiation, experiment, or evolution reshaped them. Unpredictably powerful.",
    traits: ["Mutation Pool (roll 1d6 for mutation)", "Adaptive Resistance", "Unstable Physiology"],
    abilityBonus: { constitution: 2, any: 1 },
    genres: ["Post-Apocalyptic", "Science Fiction", "Biopunk", "Zombie Apocalypse"],
    periods: ["near_future", "far_future", "alternate_history"],
    icon: "â˜¢ï¸",
  },
  {
    id: "augmented",
    name: "Augmented",
    category: "Evolved Human",
    desc: "Human enhanced beyond standard limits. The upgrades were supposed to make life easier.",
    traits: ["Enhanced Reflexes", "Neural Link", "Pain Suppression", "Implant Slot x2"],
    abilityBonus: { dexterity: 2, intelligence: 1 },
    genres: ["Cyberpunk", "Science Fiction", "Military & War"],
    periods: ["near_future", "far_future"],
    icon: "ðŸ§¬",
  },
  {
    id: "psion",
    name: "Psion",
    category: "Evolved Human",
    desc: "Evolution or experiment granted psychic abilities. The mind is both weapon and wound.",
    traits: ["Telepathy (range 30ft)", "Telekinesis", "Psychic Shield", "Psionic Drain (1/day)"],
    abilityBonus: { intelligence: 2, wisdom: 1 },
    genres: ["Science Fiction", "Cyberpunk", "Space Opera", "Horror"],
    periods: ["near_future", "far_future"],
    icon: "ðŸ§¿",
  },
  {
    id: "survivor_human",
    name: "Survivor",
    category: "Evolved Human",
    desc: "Ordinary human who endured the unthinkable. Grit incarnate. Refuses to break.",
    traits: ["Survivor's Luck", "Trauma Hardened", "Fight or Flight", "Improvised Weapons Expert"],
    abilityBonus: { wisdom: 1, constitution: 2 },
    genres: ["Post-Apocalyptic", "Survival", "Horror", "Zombie Apocalypse", "Western"],
    periods: ["all"],
    icon: "ðŸª–",
  },
  {
    id: "crossbreed",
    name: "âœ• Cross-Breed",
    category: "Cross-Breed",
    desc: "Choose any two races from your available list. Your character inherits one trait from each parent race. Ability bonuses are averaged between both.",
    traits: ["Hybrid Heritage", "1 trait from Race A", "1 trait from Race B"],
    abilityBonus: { any: 2 },
    genres: ["all"],
    periods: ["all"],
    isCrossBreed: true,
    icon: "âœ•",
  },
];

// Helper â€” filter races by genre and campaign time_period (WorldBuilder ids map via PERIOD_TAGS)
export function getRacesForGenre(primaryGenre, secondaryGenre, timePeriod) {
  const genres = [primaryGenre, secondaryGenre].filter(Boolean);
  const periodKeys =
    timePeriod && PERIOD_TAGS[timePeriod]
      ? PERIOD_TAGS[timePeriod]
      : timePeriod
        ? [timePeriod]
        : [];
  return ALL_RACES.filter((race) => {
    if (race.genres.includes("all")) return true;
    const genreMatch = race.genres.some((g) => genres.includes(g));
    if (!genreMatch) return false;
    if (!timePeriod || race.periods.includes("all")) return true;
    return race.periods.some((p) => periodKeys.includes(p));
  });
}

// â”€â”€ GENDERS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const GENDERS = [
  { id: "male", label: "Male", icon: "â™‚", pronouns: "he/him", desc: "He / Him / His" },
  { id: "female", label: "Female", icon: "â™€", pronouns: "she/her", desc: "She / Her / Hers" },
  { id: "nonbinary", label: "Non-Binary", icon: "âš§", pronouns: "they/them", desc: "They / Them / Their" },
  { id: "genderfluid", label: "Genderfluid", icon: "ðŸŒŠ", pronouns: "varies", desc: "Varies / Context-dependent" },
  { id: "agender", label: "Agender", icon: "â—‹", pronouns: "they/them", desc: "They / Them â€” or no pronoun" },
  { id: "demigender", label: "Demigender", icon: "â—‘", pronouns: "any", desc: "Partially identifies with one gender" },
  { id: "omnigender", label: "Omnigender", icon: "âˆž", pronouns: "any/all", desc: "All genders simultaneously" },
  {
    id: "synthetic_null",
    label: "Synthetic / None",
    icon: "âš™ï¸",
    pronouns: "it/its",
    desc: "For synthetic and AI races â€” no gender construct",
  },
  {
    id: "spirit_form",
    label: "Spirit-Form",
    icon: "ðŸ•¯ï¸",
    pronouns: "they/it",
    desc: "For spirits, ghosts, and ethereal entities",
  },
  {
    id: "hive_aspect",
    label: "Hive-Aspect",
    icon: "ðŸ§ ",
    pronouns: "we/our",
    desc: "For hive-mind and collective races",
  },
  {
    id: "elemental_form",
    label: "Elemental",
    icon: "ðŸŒŠ",
    pronouns: "they/it",
    desc: "For elemental and nature entities",
  },
  { id: "undisclosed", label: "Undisclosed", icon: "?", pronouns: "any", desc: "Unknown or deliberately hidden" },
];

// â”€â”€ CLASSES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const CLASSES = [
  {
    id: "warrior",
    name: "Warrior",
    icon: "âš”ï¸",
    desc: "Masters of direct combat. Frontline fighters trained to endure, adapt, and overcome.",
    hitDie: "d10",
    primaryStats: ["strength", "constitution"],
    savingThrows: ["strength", "constitution"],
    armorProf: ["Light", "Medium", "Heavy", "Shields"],
    weaponProf: ["Simple", "Martial"],
    skills: ["Athletics", "Intimidation", "Perception", "Survival", "History", "Acrobatics"],
    skillCount: 2,
    paths: ["Iron Warden", "Blood Reaver", "Storm Duelist"],
    genres: ["all"],
    desc_long:
      "Warriors dominate the battlefield through martial excellence. Each hit builds momentum.",
  },
  {
    id: "rogue",
    name: "Rogue",
    icon: "ðŸ—¡ï¸",
    desc: "Skilled operatives. Experts in stealth, deception, and precision strikes from the shadows.",
    hitDie: "d8",
    primaryStats: ["dexterity", "intelligence"],
    savingThrows: ["dexterity", "intelligence"],
    armorProf: ["Light"],
    weaponProf: ["Simple", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
    skills: [
      "Stealth",
      "Deception",
      "Sleight of Hand",
      "Perception",
      "Investigation",
      "Persuasion",
      "Athletics",
      "Acrobatics",
    ],
    skillCount: 4,
    paths: ["Shadow Blade", "Mastermind", "Scout"],
    genres: ["all"],
  },
  {
    id: "arcanist",
    name: "Arcanist",
    icon: "âœ¨",
    desc: "Wielders of raw magical force. Vast destructive power held in a fragile vessel.",
    hitDie: "d6",
    primaryStats: ["intelligence", "wisdom"],
    savingThrows: ["intelligence", "wisdom"],
    armorProf: [],
    weaponProf: ["Daggers", "Quarterstaffs", "Light Crossbows"],
    skills: ["Arcana", "History", "Investigation", "Medicine", "Religion", "Insight"],
    skillCount: 2,
    paths: ["Elementalist", "Void Caller", "Chronomancer"],
    genres: ["Fantasy", "Mythology & Legend", "Gothic Romance", "Isekai / Portal Fantasy"],
  },
  {
    id: "warden",
    name: "Warden",
    icon: "ðŸ›¡ï¸",
    desc: "Sworn protectors. They stand between the enemy and everyone worth protecting.",
    hitDie: "d10",
    primaryStats: ["strength", "charisma"],
    savingThrows: ["wisdom", "charisma"],
    armorProf: ["Light", "Medium", "Heavy", "Shields"],
    weaponProf: ["Simple", "Martial"],
    skills: ["Athletics", "Insight", "Intimidation", "Medicine", "Persuasion", "Religion"],
    skillCount: 2,
    paths: ["Oath of the Shield", "Oath of Vengeance", "Oath of the Realm"],
    genres: ["all"],
  },
  {
    id: "hunter",
    name: "Hunter",
    icon: "ðŸ¹",
    desc: "Trackers, rangers, and survivalists. At home in any terrain, comfortable with any prey.",
    hitDie: "d8",
    primaryStats: ["dexterity", "wisdom"],
    savingThrows: ["strength", "dexterity"],
    armorProf: ["Light", "Medium", "Shields"],
    weaponProf: ["Simple", "Martial"],
    skills: [
      "Animal Handling",
      "Athletics",
      "Insight",
      "Investigation",
      "Nature",
      "Perception",
      "Stealth",
      "Survival",
    ],
    skillCount: 3,
    paths: ["Beastmaster", "Sharpshooter", "Stalker"],
    genres: ["all"],
  },
  {
    id: "seeker",
    name: "Seeker",
    icon: "ðŸ”®",
    desc: "Mystics who pierce the veil. They see the world as it is beneath the surface.",
    hitDie: "d6",
    primaryStats: ["wisdom", "charisma"],
    savingThrows: ["wisdom", "charisma"],
    armorProf: ["Light"],
    weaponProf: ["Simple"],
    skills: ["Arcana", "History", "Insight", "Investigation", "Nature", "Perception", "Religion", "Survival"],
    skillCount: 2,
    paths: ["Oracle", "Void Walker", "Soul Binder"],
    genres: ["Fantasy", "Supernatural / Paranormal", "Horror", "Gothic Romance", "Lovecraftian"],
  },
  {
    id: "speaker",
    name: "Speaker",
    icon: "ðŸŽ­",
    desc: "Masters of influence. Words are their weapons and social dynamics their battlefield.",
    hitDie: "d8",
    primaryStats: ["charisma", "wisdom"],
    savingThrows: ["dexterity", "charisma"],
    armorProf: ["Light"],
    weaponProf: ["Simple"],
    skills: ["Deception", "Insight", "Intimidation", "Perception", "Performance", "Persuasion"],
    skillCount: 3,
    paths: ["Deceiver", "Commander", "Bard of the Rift"],
    genres: ["all"],
  },
  {
    id: "catalyst",
    name: "Catalyst",
    icon: "âš—ï¸",
    desc: "Alchemists, artificers, and support specialists. They win fights through preparation.",
    hitDie: "d8",
    primaryStats: ["intelligence", "constitution"],
    savingThrows: ["constitution", "intelligence"],
    armorProf: ["Light", "Medium"],
    weaponProf: ["Simple"],
    skills: [
      "Arcana",
      "History",
      "Investigation",
      "Medicine",
      "Nature",
      "Perception",
      "Sleight of Hand",
      "Survival",
    ],
    skillCount: 2,
    paths: ["Alchemist", "Artificer", "Battle Medic"],
    genres: ["Fantasy", "Steampunk", "Dieselpunk", "Science Fiction"],
  },

  {
    id: "netrunner",
    name: "Netrunner",
    icon: "ðŸ’»",
    desc: "Digital infiltrators who fight wars in cyberspace. Reality is just the slower network.",
    hitDie: "d6",
    primaryStats: ["intelligence", "dexterity"],
    savingThrows: ["intelligence", "dexterity"],
    armorProf: ["Light"],
    weaponProf: ["Simple", "Sidearms"],
    skills: ["Hacking", "Investigation", "Technology", "Stealth", "Deception", "Engineering"],
    skillCount: 4,
    paths: ["Ice Breaker", "Ghost Signal", "Architect"],
    genres: ["Cyberpunk", "Science Fiction", "Space Opera"],
  },
  {
    id: "gunslinger",
    name: "Gunslinger",
    icon: "ðŸ”«",
    desc: "Speed and precision with ranged weapons. The hand is faster than the eye and the mind faster than both.",
    hitDie: "d8",
    primaryStats: ["dexterity", "wisdom"],
    savingThrows: ["dexterity", "constitution"],
    armorProf: ["Light", "Medium"],
    weaponProf: ["Simple", "Firearms", "Martial"],
    skills: ["Acrobatics", "Perception", "Stealth", "Athletics", "Insight", "Sleight of Hand"],
    skillCount: 3,
    paths: ["Deadeye", "Outlaw", "Trick Shot"],
    genres: ["Western", "Weird West", "Cyberpunk", "Post-Apocalyptic", "Dieselpunk"],
  },
  {
    id: "pilot",
    name: "Pilot",
    icon: "ðŸš€",
    desc: "Extraordinary skill with vehicles, ships, and craft. At their best when moving at speed.",
    hitDie: "d8",
    primaryStats: ["dexterity", "intelligence"],
    savingThrows: ["dexterity", "intelligence"],
    armorProf: ["Light"],
    weaponProf: ["Simple", "Vehicle Weapons", "Sidearms"],
    skills: ["Piloting", "Navigation", "Engineering", "Perception", "Acrobatics", "Technology"],
    skillCount: 3,
    paths: ["Ace", "Smuggler", "War Pilot"],
    genres: ["Science Fiction", "Space Opera", "Military & War", "Dieselpunk"],
  },
  {
    id: "medic",
    name: "Combat Medic",
    icon: "ðŸ©º",
    desc: "Field physicians who keep allies alive and occasionally end enemies. Their tools cut both ways.",
    hitDie: "d8",
    primaryStats: ["wisdom", "intelligence"],
    savingThrows: ["wisdom", "constitution"],
    armorProf: ["Light", "Medium"],
    weaponProf: ["Simple", "Medical Instruments"],
    skills: ["Medicine", "Science", "Insight", "Perception", "Persuasion", "Survival"],
    skillCount: 3,
    paths: ["Field Surgeon", "Bio-Enhancer", "Trauma Specialist"],
    genres: ["Military & War", "Science Fiction", "Post-Apocalyptic", "Cyberpunk"],
  },
  {
    id: "monk",
    name: "Monk",
    icon: "ðŸ¥‹",
    desc: "Masters of inner power and unarmed combat. The body is the weapon. The mind is the trigger.",
    hitDie: "d8",
    primaryStats: ["dexterity", "wisdom"],
    savingThrows: ["strength", "dexterity"],
    armorProf: [],
    weaponProf: ["Simple", "Shortswords"],
    skills: ["Acrobatics", "Athletics", "History", "Insight", "Religion", "Stealth"],
    skillCount: 2,
    paths: ["Way of the Open Hand", "Way of Shadow", "Way of the Elements"],
    genres: ["Martial Arts / Wuxia", "Fantasy", "Mythology & Legend"],
  },
  {
    id: "shaman",
    name: "Shaman",
    icon: "ðŸŒ¿",
    desc: "Conduit between the living and the spirit world. Negotiates where others fight.",
    hitDie: "d8",
    primaryStats: ["wisdom", "charisma"],
    savingThrows: ["wisdom", "charisma"],
    armorProf: ["Light", "Medium", "Shields"],
    weaponProf: ["Simple"],
    skills: ["Nature", "Religion", "Survival", "Medicine", "Insight", "Animal Handling"],
    skillCount: 2,
    paths: ["Ancestor Caller", "Nature Warden", "Spirit Walker"],
    genres: ["Fantasy", "Mythology & Legend", "Weird West", "Survival"],
  },
  {
    id: "engineer",
    name: "Engineer",
    icon: "ðŸ”§",
    desc: "Builders, fixers, and problem-solvers. Can construct or destroy anything given enough time.",
    hitDie: "d8",
    primaryStats: ["intelligence", "constitution"],
    savingThrows: ["constitution", "intelligence"],
    armorProf: ["Light", "Medium"],
    weaponProf: ["Simple", "Improvised", "Firearms"],
    skills: ["Engineering", "Technology", "Investigation", "Athletics", "Science", "Mechanics"],
    skillCount: 3,
    paths: ["Demolitions", "Fabricator", "Drone Commander"],
    genres: ["Science Fiction", "Cyberpunk", "Steampunk", "Dieselpunk", "Military & War"],
  },
  {
    id: "berserker",
    name: "Berserker",
    icon: "ðŸ˜¤",
    desc: "Primal rage as a weapon. When the rage takes over, there is very little left but the fight.",
    hitDie: "d12",
    primaryStats: ["strength", "constitution"],
    savingThrows: ["strength", "constitution"],
    armorProf: ["Light", "Medium", "Shields"],
    weaponProf: ["Simple", "Martial"],
    skills: ["Athletics", "Intimidation", "Nature", "Perception", "Survival"],
    skillCount: 2,
    paths: ["Totem Warrior", "Frenzied", "Ancestral Guardian"],
    genres: ["Fantasy", "Post-Apocalyptic", "Mythology & Legend", "Survival", "Weird West"],
  },
  {
    id: "psionicist",
    name: "Psionicist",
    icon: "ðŸ§¿",
    desc: "Psychic warriors who weaponise the mind. Thought is faster than any bullet.",
    hitDie: "d8",
    primaryStats: ["intelligence", "wisdom"],
    savingThrows: ["intelligence", "wisdom"],
    armorProf: ["Light"],
    weaponProf: ["Simple"],
    skills: ["Insight", "Investigation", "Perception", "Science", "History", "Medicine"],
    skillCount: 3,
    paths: ["Telepath", "Telekinetic", "Mind Blade"],
    genres: ["Science Fiction", "Cyberpunk", "Space Opera", "Cosmic Horror"],
  },
];

// â”€â”€ BACKGROUNDS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const BACKGROUNDS = [
  {
    id: "soldier",
    name: "Soldier",
    icon: "ðŸŽ–ï¸",
    desc: "Served in a military force. Knows discipline, tactics, and the cost of orders.",
    skills: ["Athletics", "Intimidation"],
    tools: ["Dice Set", "Vehicles (Land)"],
    languages: 1,
    feature: "Military Rank",
    genres: ["all"],
  },
  {
    id: "criminal",
    name: "Criminal",
    icon: "ðŸ—ï¸",
    desc: "Operated outside the law. Contacts in the underworld and an eye for exploitable systems.",
    skills: ["Deception", "Stealth"],
    tools: ["Thieves Tools", "Gaming Set"],
    languages: 0,
    feature: "Criminal Contact",
    genres: ["all"],
  },
  {
    id: "scholar",
    name: "Scholar",
    icon: "ðŸ“š",
    desc: "Spent years in formal study. Knows more theory than practical survival.",
    skills: ["Arcana", "History"],
    tools: [],
    languages: 2,
    feature: "Researcher",
    genres: ["all"],
  },
  {
    id: "noble",
    name: "Noble",
    icon: "ðŸ‘‘",
    desc: "Born into privilege. A name that opens doors â€” and closes others.",
    skills: ["History", "Persuasion"],
    tools: ["Gaming Set"],
    languages: 1,
    feature: "Position of Privilege",
    genres: ["all"],
  },
  {
    id: "outlander",
    name: "Outlander",
    icon: "ðŸŒ²",
    desc: "Raised far from civilisation. Knows the wilds better than any city street.",
    skills: ["Athletics", "Survival"],
    tools: ["Musical Instrument"],
    languages: 1,
    feature: "Wanderer",
    genres: ["all"],
  },
  {
    id: "acolyte",
    name: "Acolyte",
    icon: "ðŸ•¯ï¸",
    desc: "Devoted to a faith or philosophy. Convictions that shaped every decision.",
    skills: ["Insight", "Religion"],
    tools: [],
    languages: 2,
    feature: "Shelter of the Faithful",
    genres: ["Fantasy", "Mythology & Legend", "Gothic Romance"],
  },
  {
    id: "entertainer",
    name: "Entertainer",
    icon: "ðŸŽª",
    desc: "Performed for crowds. Reads a room instinctively and plays to it perfectly.",
    skills: ["Acrobatics", "Performance"],
    tools: ["Disguise Kit", "Musical Instrument"],
    languages: 0,
    feature: "By Popular Demand",
    genres: ["all"],
  },
  {
    id: "merchant",
    name: "Merchant",
    icon: "âš–ï¸",
    desc: "Traded goods across regions. Knows the value of everything and the price of loyalty.",
    skills: ["Insight", "Persuasion"],
    tools: ["Navigator Tools", "Vehicles (Water)"],
    languages: 1,
    feature: "Guild Membership",
    genres: ["all"],
  },
  {
    id: "hermit",
    name: "Hermit",
    icon: "ðŸ§˜",
    desc: "Lived alone in silence. Discovered something significant while there.",
    skills: ["Medicine", "Religion"],
    tools: ["Herbalism Kit"],
    languages: 1,
    feature: "Discovery",
    genres: ["all"],
  },
  {
    id: "spy",
    name: "Spy",
    icon: "ðŸ•µï¸",
    desc: "Operated undercover. Became so many people they had to remember who they were.",
    skills: ["Deception", "Stealth"],
    tools: ["Disguise Kit", "Forgery Kit"],
    languages: 1,
    feature: "False Identity",
    genres: ["all"],
  },
  {
    id: "street_urchin",
    name: "Street Urchin",
    icon: "ðŸšï¸",
    desc: "Survived on city streets. Knows every system can be gamed by someone desperate enough.",
    skills: ["Sleight of Hand", "Stealth"],
    tools: ["Thieves Tools", "Disguise Kit"],
    languages: 0,
    feature: "City Secrets",
    genres: ["all"],
  },
  {
    id: "explorer",
    name: "Explorer",
    icon: "ðŸ§­",
    desc: "Charted unknown territories. Left maps behind and found things no map could hold.",
    skills: ["Perception", "Survival"],
    tools: ["Cartographer Tools"],
    languages: 1,
    feature: "Discovery",
    genres: ["all"],
  },
  {
    id: "revolutionary",
    name: "Revolutionary",
    icon: "âœŠ",
    desc: "Fought against a system they believed was wrong. Some call it heroism.",
    skills: ["Deception", "Stealth"],
    tools: ["Forgery Kit"],
    languages: 1,
    feature: "Hidden Network",
    genres: ["all"],
  },
  {
    id: "healer",
    name: "Healer",
    icon: "ðŸ©º",
    desc: "Tended the wounded and dying. Knows the body's limits and how to push past them.",
    skills: ["Medicine", "Insight"],
    tools: ["Herbalism Kit", "Healer's Kit"],
    languages: 1,
    feature: "Healer's Gift",
    genres: ["all"],
  },
  {
    id: "pirate",
    name: "Pirate",
    icon: "âš“",
    desc: "Sailed under a banner the law didn't recognise. Freedom at any cost.",
    skills: ["Athletics", "Perception"],
    tools: ["Navigator Tools", "Vehicles (Water)"],
    languages: 1,
    feature: "Bad Reputation",
    genres: ["Pirate / Age of Sail", "Western", "Weird West"],
  },
  {
    id: "gladiator",
    name: "Gladiator",
    icon: "ðŸŸï¸",
    desc: "Fought for survival in an arena. The crowd's roar is home.",
    skills: ["Athletics", "Performance"],
    tools: ["Unusual Weapon"],
    languages: 0,
    feature: "By Popular Demand",
    genres: ["Fantasy", "Mythology & Legend", "Science Fiction"],
  },
  {
    id: "scientist",
    name: "Scientist",
    icon: "ðŸ”¬",
    desc: "Dedicated to empirical understanding. Nothing is unexplainable â€” just not yet explained.",
    skills: ["Science", "Investigation"],
    tools: ["Scientific Equipment", "Lab Kit"],
    languages: 2,
    feature: "Research Grant",
    genres: ["Science Fiction", "Cyberpunk", "Biopunk", "Steampunk"],
  },
  {
    id: "hacker",
    name: "Hacker",
    icon: "ðŸ’»",
    desc: "Born in digital spaces. Every system has a door if you know where to knock.",
    skills: ["Hacking", "Technology"],
    tools: ["Custom Rig", "Lockpick Software"],
    languages: 0,
    feature: "Backdoor Access",
    genres: ["Cyberpunk", "Science Fiction"],
  },
  {
    id: "corporate",
    name: "Corporate",
    icon: "ðŸ’¼",
    desc: "Once inside the machine. Now something else â€” but the resources remain.",
    skills: ["Persuasion", "Insight"],
    tools: ["Encrypted Comm", "Executive Pass"],
    languages: 1,
    feature: "Corporate Access",
    genres: ["Cyberpunk", "Science Fiction", "Noir / Detective"],
  },
  {
    id: "cultist",
    name: "Former Cultist",
    icon: "ðŸ‘ï¸",
    desc: "Believed in something terrible. Escaped. The beliefs left marks that don't wash off.",
    skills: ["Religion", "Deception"],
    tools: ["Dark Ritual Components"],
    languages: 1,
    feature: "Cult Insider",
    genres: ["Horror", "Lovecraftian", "Cosmic Horror", "Supernatural / Paranormal"],
  },
  {
    id: "pilot_bg",
    name: "Pilot",
    icon: "ðŸš€",
    desc: "Flew things most people said couldn't be flown. Instinct beats instruments every time.",
    skills: ["Piloting", "Technology"],
    tools: ["Navigation Charts", "Repair Kit"],
    languages: 1,
    feature: "Never Lost",
    genres: ["Science Fiction", "Space Opera", "Dieselpunk", "Military & War"],
  },
  {
    id: "nomad",
    name: "Nomad",
    icon: "ðŸ›¤ï¸",
    desc: "No permanent home. No fixed allegiances. The road is the only constant.",
    skills: ["Survival", "Perception"],
    tools: ["Vehicles (Land)", "Repair Kit"],
    languages: 1,
    feature: "Always Moving",
    genres: ["Western", "Post-Apocalyptic", "Cyberpunk", "Survival"],
  },
  {
    id: "monk_bg",
    name: "Monastic Order",
    icon: "ðŸ¯",
    desc: "Trained in a discipline spanning generations. Body and mind as one instrument.",
    skills: ["Athletics", "Religion"],
    tools: ["Calligrapher's Supplies"],
    languages: 2,
    feature: "Monastic Tradition",
    genres: ["Martial Arts / Wuxia", "Fantasy", "Mythology & Legend"],
  },
  {
    id: "journalist",
    name: "Journalist",
    icon: "ðŸ“°",
    desc: "Chased truth into places truth didn't want to be found. Has the sources to prove it.",
    skills: ["Investigation", "Persuasion"],
    tools: ["Recording Gear", "Press Pass"],
    languages: 1,
    feature: "Press Access",
    genres: ["Noir / Detective", "Cyberpunk", "Political Intrigue"],
  },
  {
    id: "bounty_hunter",
    name: "Bounty Hunter",
    icon: "ðŸŽ¯",
    desc: "Gets paid to find people who don't want to be found. Very good at the job.",
    skills: ["Perception", "Intimidation"],
    tools: ["Manacles", "Tracking Kit"],
    languages: 1,
    feature: "Quarry Knowledge",
    genres: ["Western", "Cyberpunk", "Science Fiction", "Post-Apocalyptic"],
  },
];

// â”€â”€ ABILITY SCORES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const ABILITY_SCORES = [
  {
    id: "strength",
    name: "Strength",
    abbr: "STR",
    desc: "Physical power. Melee attacks, carrying, breaking, climbing.",
  },
  {
    id: "dexterity",
    name: "Dexterity",
    abbr: "DEX",
    desc: "Agility and reflexes. Ranged attacks, stealth, initiative, lockpicking.",
  },
  {
    id: "constitution",
    name: "Constitution",
    abbr: "CON",
    desc: "Endurance and toughness. Hit points, stamina, concentration, poison resistance.",
  },
  {
    id: "intelligence",
    name: "Intelligence",
    abbr: "INT",
    desc: "Reasoning and memory. Knowledge, investigation, arcana, hacking, engineering.",
  },
  {
    id: "wisdom",
    name: "Wisdom",
    abbr: "WIS",
    desc: "Perception and insight. Awareness, intuition, willpower, navigation.",
  },
  {
    id: "charisma",
    name: "Charisma",
    abbr: "CHA",
    desc: "Force of personality. Persuasion, deception, leadership, performance.",
  },
];

export const ROLL_SCORE_TABLE = [
  { rolls: [1, 2, 3, 4], score: 8, label: "Weak", color: "#C04040" },
  { rolls: [5, 6, 7, 8], score: 10, label: "Average", color: "#8B6A0E" },
  { rolls: [9, 10, 11, 12], score: 12, label: "Capable", color: "#4A7FD4" },
  { rolls: [13, 14, 15, 16], score: 14, label: "Strong", color: "#1A6B2A" },
  { rolls: [17, 18, 19, 20], score: 16, label: "Exceptional", color: "#C9A84C" },
];

// â”€â”€ SKILLS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const ALL_SKILLS = [
  { name: "Athletics", stat: "strength", category: "Physical", desc: "Climbing, jumping, swimming, and feats of raw physical power." },
  { name: "Acrobatics", stat: "dexterity", category: "Physical", desc: "Balance, tumbling, parkour, and aerial manoeuvres." },
  { name: "Stealth", stat: "dexterity", category: "Physical", desc: "Moving silently, hiding, and avoiding detection." },
  { name: "Sleight of Hand", stat: "dexterity", category: "Physical", desc: "Pickpocketing, card tricks, concealment, and manual precision." },
  { name: "Endurance", stat: "constitution", category: "Physical", desc: "Sustaining effort, resisting exhaustion, and surviving harsh conditions." },
  { name: "Investigation", stat: "intelligence", category: "Mental", desc: "Searching for clues, analysing evidence, and deductive reasoning." },
  { name: "Arcana", stat: "intelligence", category: "Mental", desc: "Knowledge of magic, spells, mystical creatures, and arcane traditions." },
  { name: "History", stat: "intelligence", category: "Mental", desc: "Recalling historical events, lore, legends, and cultural knowledge." },
  { name: "Nature", stat: "intelligence", category: "Mental", desc: "Knowledge of the natural world, plants, animals, and weather." },
  { name: "Religion", stat: "intelligence", category: "Mental", desc: "Knowledge of deities, rites, holy symbols, and theological doctrine." },
  { name: "Medicine", stat: "wisdom", category: "Mental", desc: "Diagnosing and treating injuries, diseases, and poisons." },
  { name: "Insight", stat: "wisdom", category: "Mental", desc: "Reading intentions, detecting lies, and understanding motivations." },
  { name: "Perception", stat: "wisdom", category: "Mental", desc: "Noticing details, detecting presence, and awareness of surroundings." },
  { name: "Survival", stat: "wisdom", category: "Mental", desc: "Tracking, foraging, navigating, and enduring the wilderness." },
  { name: "Animal Handling", stat: "wisdom", category: "Mental", desc: "Calming, training, and communicating with animals." },
  { name: "Persuasion", stat: "charisma", category: "Social", desc: "Convincing others through logic, charm, or emotional appeal." },
  { name: "Deception", stat: "charisma", category: "Social", desc: "Lying convincingly, bluffing, and misleading others." },
  { name: "Intimidation", stat: "charisma", category: "Social", desc: "Coercing others through fear, threats, or menacing presence." },
  { name: "Performance", stat: "charisma", category: "Social", desc: "Acting, music, oratory, and captivating an audience." },
  { name: "Leadership", stat: "charisma", category: "Social", desc: "Inspiring allies, commanding troops, and directing group action." },
  { name: "Streetwise", stat: "charisma", category: "Social", desc: "Understanding urban underworld culture, gang dynamics, and city networks." },
  { name: "Engineering", stat: "intelligence", category: "Technical", desc: "Building, repairing, and understanding mechanical and structural systems." },
  { name: "Technology", stat: "intelligence", category: "Technical", desc: "Using, understanding, and interfacing with advanced technological devices." },
  { name: "Hacking", stat: "intelligence", category: "Technical", desc: "Penetrating digital security systems, extracting data, and cyber sabotage." },
  { name: "Science", stat: "intelligence", category: "Technical", desc: "Applied knowledge of biology, chemistry, physics, and related disciplines." },
  { name: "Machine Learning", stat: "intelligence", category: "Technical", desc: "Training, interrogating, and manipulating AI and machine learning systems." },
  { name: "Mechanics", stat: "intelligence", category: "Technical", desc: "Repairing engines, vehicles, weapons, and complex mechanical devices." },
  { name: "Explosives", stat: "intelligence", category: "Technical", desc: "Constructing, placing, and defusing explosive devices safely (or not)." },
  { name: "Cryptography", stat: "intelligence", category: "Technical", desc: "Encoding and decoding messages, breaking ciphers, and secure communication." },
  { name: "Navigation", stat: "wisdom", category: "Technical", desc: "Charting courses by stars, instruments, or instinct across any terrain or space." },
  { name: "Piloting", stat: "dexterity", category: "Technical", desc: "Operating aircraft, spacecraft, ground vehicles, and nautical vessels." },
  { name: "Demolitions", stat: "intelligence", category: "Technical", desc: "Strategic destruction â€” walls, bridges, vaults, and fortifications." },
  { name: "First Aid", stat: "wisdom", category: "Technical", desc: "Immediate triage and stabilisation in the field without medical equipment." },
  { name: "Ritual Magic", stat: "intelligence", category: "Arcane", desc: "Performing magical rites, summoning, and ancient ceremonies." },
  { name: "Divination", stat: "wisdom", category: "Arcane", desc: "Reading omens, interpreting dreams, and sensing future possibilities." },
  { name: "Spirit Lore", stat: "wisdom", category: "Arcane", desc: "Knowledge of spirits, the afterlife, possession, and ethereal forces." },
  { name: "Alchemy", stat: "intelligence", category: "Arcane", desc: "Creating potions, poisons, reagents, and transmutative compounds." },
  { name: "Psionics", stat: "wisdom", category: "Arcane", desc: "Controlling and understanding psychic abilities, mental attacks, and shields." },
  { name: "Crafting", stat: "intelligence", category: "Craft", desc: "Creating weapons, armour, tools, and equipment from raw materials." },
  { name: "Cooking", stat: "wisdom", category: "Craft", desc: "Preparing food that provides mechanical benefits â€” morale, healing, buffs." },
  { name: "Forgery", stat: "dexterity", category: "Craft", desc: "Creating convincing fake documents, identities, seals, and signatures." },
  { name: "Disguise", stat: "charisma", category: "Craft", desc: "Creating and maintaining convincing physical disguises and personas." },
  { name: "Lore", stat: "intelligence", category: "Craft", desc: "Deep esoteric knowledge of a specific subject â€” monsters, geography, politics." },
  { name: "Gambling", stat: "charisma", category: "Craft", desc: "Reading the table, bluffing, and calculating odds under pressure." },
];

// â”€â”€ FEATS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const FEATS = [
  { id: "alert", name: "Alert", level: 1, desc: "+5 to initiative. Cannot be surprised while conscious. Unseen attackers have no advantage against you.", prereq: null },
  { id: "tough", name: "Tough", level: 1, desc: "+2 HP per level, retroactive. Hardened body from birth or brutal conditioning.", prereq: null },
  { id: "lucky", name: "Lucky", level: 1, desc: "3 luck points per rest. Spend to reroll any d20 and take either result.", prereq: null },
  { id: "linguist", name: "Linguist", level: 1, desc: "Learn 3 additional languages. Create ciphers that only you and trusted allies can decode.", prereq: null },
  { id: "magic_initiate", name: "Magic Initiate", level: 1, desc: "Learn 2 cantrips and 1 first-level spell from any class. Use charisma to cast.", prereq: null },
  { id: "skilled", name: "Skilled", level: 1, desc: "Gain proficiency in any 3 skills or tools of your choice.", prereq: null },
  { id: "mobile", name: "Mobile", level: 2, desc: "+10 speed. Dash ignores difficult terrain. When you attack a creature you don't provoke opportunity attacks from it.", prereq: null },
  { id: "observant", name: "Observant", level: 2, desc: "+5 passive Perception and Investigation. Can lip-read anyone you can see speaking.", prereq: null },
  { id: "healer_feat", name: "Healer", level: 2, desc: "Healer's Kit stabilises and restores 1d6+4+level HP. Can restore HP once per creature per rest.", prereq: null },
  { id: "resilient", name: "Resilient", level: 3, desc: "Gain proficiency in one saving throw of your choice. +1 to the chosen ability score.", prereq: null },
  { id: "dual_wielder", name: "Dual Wielder", level: 3, desc: "+1 AC while wielding two weapons. Use non-light weapons for two-weapon fighting. Draw or stow two weapons in one action.", prereq: "dexterity 13" },
  { id: "sharpshooter", name: "Sharpshooter", level: 3, desc: "Ignore half and three-quarters cover. No disadvantage at long range. Take -5 to hit for +10 damage.", prereq: "dexterity 13" },
  { id: "grappler", name: "Grappler", level: 4, desc: "Advantage on attacks against grappled creatures. Can pin grappled creatures â€” both are restrained.", prereq: "strength 13" },
  { id: "sentinel", name: "Sentinel", level: 4, desc: "Opportunity attacks reduce speed to 0. Reaction attack when adjacent ally is hit. Disengage doesn't prevent your opportunity attack.", prereq: null },
  { id: "charger", name: "Charger", level: 4, desc: "Bonus attack or push after Dash. +5 damage if attack hits after Dash. Targets have disadvantage on opportunity attacks against you this turn.", prereq: null },
  { id: "inspiring_leader", name: "Inspiring Leader", level: 5, desc: "10 minute speech: grant temporary HP equal to level + CHA modifier to up to 6 allies. Once per rest.", prereq: "charisma 13" },
  { id: "war_caster", name: "War Caster", level: 5, desc: "Advantage on concentration saves. Somatic components with hands full. Cast spells as opportunity attacks.", prereq: "arcanist or seeker or catalyst" },
  { id: "polearm_master", name: "Polearm Master", level: 5, desc: "Bonus attack with the butt of your weapon. Opportunity attacks against creatures entering reach. +1 attack and damage.", prereq: "strength 13" },
  { id: "great_weapon", name: "Great Weapon Master", level: 6, desc: "On critical or kill: bonus attack. Take -5 to hit for +10 damage with heavy weapons.", prereq: "strength 15" },
  { id: "shield_master", name: "Shield Master", level: 6, desc: "Shove as bonus action if you attack. Add shield bonus to Dex saves. No damage on successful Dex save.", prereq: null },
  { id: "elemental_adept", name: "Elemental Adept", level: 6, desc: "Your spells of chosen element ignore resistance. Minimum die roll of 2 for damage dice. Can be taken multiple times.", prereq: "spellcasting" },
  { id: "mage_slayer", name: "Mage Slayer", level: 7, desc: "Reaction attack when adjacent creature casts. Target has disadvantage on concentration. Advantage on saves vs adjacent spells.", prereq: null },
  { id: "crossbow_expert", name: "Crossbow Expert", level: 7, desc: "Ignore loading property. No disadvantage in melee. Bonus attack with hand crossbow after one-handed attack.", prereq: "dexterity 13" },
  { id: "mounted_combatant", name: "Mounted Combatant", level: 7, desc: "Advantage on melee vs unmounted smaller creatures. Force attack onto you instead of mount. Mount succeeds on Dex saves automatically.", prereq: null },
  { id: "shadow_touched", name: "Shadow Touched", level: 8, desc: "Learn Invisibility. Learn 1 illusion or necromancy spell. Cast each once per rest for free. +1 to spellcasting stat.", prereq: null },
  { id: "fey_touched", name: "Fey Touched", level: 8, desc: "Learn Misty Step. Learn 1 divination or enchantment spell. Cast each once per rest for free. +1 to spellcasting stat.", prereq: null },
  { id: "gift_of_alacrity", name: "Gift of Alacrity", level: 8, desc: "+1d8 to initiative rolls. Advantage on first attack of combat if you are not surprised.", prereq: null },
  { id: "telekinetic", name: "Telekinetic", level: 9, desc: "Learn Mage Hand (invisible). Bonus action shove 5ft. +1 to spellcasting stat.", prereq: "intelligence or wisdom 13" },
  { id: "telepathic", name: "Telepathic", level: 9, desc: "Speak telepathically to anyone within 60ft. Cast Detect Thoughts once per rest free. +1 to spellcasting stat.", prereq: "intelligence or charisma 13" },
  { id: "metamagic_adept", name: "Metamagic Adept", level: 9, desc: "Learn 2 Metamagic options. Gain 2 sorcery points. Can spend points on your chosen Metamagic.", prereq: "spellcasting" },
  { id: "crusher", name: "Crusher", level: 10, desc: "Once per turn: push target 5ft on bludgeoning hit. Critical hit: allies have advantage vs that creature this round.", prereq: "strength or constitution 13" },
  { id: "slasher", name: "Slasher", level: 10, desc: "Once per turn: reduce target speed by 10ft on slashing hit. Critical: target has disadvantage on attacks until your next turn.", prereq: "strength or dexterity 13" },
  { id: "piercer", name: "Piercer", level: 10, desc: "Once per turn: reroll one piercing damage die on hit. On critical: roll one extra damage die.", prereq: "strength or dexterity 13" },
  { id: "eldritch_adept", name: "Eldritch Adept", level: 12, desc: "Learn one Eldritch Invocation from the warlock list. If it has prerequisites, you must meet them.", prereq: "warlock or Pact Magic" },
  { id: "ritual_caster", name: "Ritual Caster", level: 12, desc: "Learn 2 ritual spells and a spellbook. Add rituals you find. Cannot cast them as regular spells without slots.", prereq: "intelligence or wisdom 13" },
  { id: "ki_adept", name: "Ki Adept", level: 14, desc: "Gain 4 additional Ki points. Learn 2 additional Ki-powered techniques from the monk list.", prereq: "monk level 5" },
  { id: "mythic_presence", name: "Mythic Presence", level: 16, desc: "Once per long rest: for 1 minute, all enemies who can see you must succeed on Wisdom save or be frightened.", prereq: "charisma 17" },
  { id: "avatar_of_power", name: "Avatar of Power", level: 18, desc: "Once per long rest: transform for 1 minute. +4 to all stats, resistance to all damage, fly speed 60ft.", prereq: "level 18" },
  { id: "legendary_will", name: "Legendary Will", level: 20, desc: "Cannot be charmed, frightened, or possessed. When you fail a saving throw you may spend a Legendary Point to succeed instead (3/day).", prereq: "level 20" },
];

export const LEVEL_PROGRESSION = [
  { level: 1, campaignsNeeded: 0, usb: 2, featUnlock: 1, spikeName: null, desc: "Starting level. Choose 1 feat." },
  { level: 2, campaignsNeeded: 1, usb: 2, featUnlock: 1, spikeName: null, desc: "First campaign complete. Unlock Level 2 feats." },
  { level: 3, campaignsNeeded: 2, usb: 2, featUnlock: 1, spikeName: "First Identity Spike", desc: "Choose your Path. Unlock Level 3 feats. Subclass / Path unlock." },
  { level: 4, campaignsNeeded: 4, usb: 2, featUnlock: 1, spikeName: null, desc: "Ability score improvement available." },
  { level: 5, campaignsNeeded: 6, usb: 3, featUnlock: 1, spikeName: null, desc: "USB increases to +3. Tier 2 begins." },
  { level: 6, campaignsNeeded: 8, usb: 3, featUnlock: 1, spikeName: "Core Build Spike", desc: "Strong synergy abilities. Unlock Level 6 feats." },
  { level: 7, campaignsNeeded: 11, usb: 3, featUnlock: 1, spikeName: null, desc: "New class feature unlocked." },
  { level: 8, campaignsNeeded: 14, usb: 3, featUnlock: 1, spikeName: null, desc: "Ability score improvement. Unlock Level 8 feats." },
  { level: 9, campaignsNeeded: 18, usb: 4, featUnlock: 1, spikeName: "Expansion Spike", desc: "New mechanics introduced. USB +4. Path evolves." },
  { level: 10, campaignsNeeded: 22, usb: 4, featUnlock: 1, spikeName: null, desc: "Major class feature milestone." },
  { level: 11, campaignsNeeded: 27, usb: 4, featUnlock: 1, spikeName: null, desc: "Paragon tier begins. Mastery builds." },
  { level: 12, campaignsNeeded: 32, usb: 4, featUnlock: 1, spikeName: "Mastery Spike", desc: "Build optimisation. Unlock Level 12 feats. Ability score improvement." },
  { level: 13, campaignsNeeded: 38, usb: 5, featUnlock: 1, spikeName: null, desc: "USB +5. Identity deepens." },
  { level: 14, campaignsNeeded: 44, usb: 5, featUnlock: 1, spikeName: null, desc: "Path transcendence approaching." },
  { level: 15, campaignsNeeded: 51, usb: 5, featUnlock: 1, spikeName: "Pre-Mythic Spike", desc: "High power scaling. Path Transcendence unlocked." },
  { level: 16, campaignsNeeded: 58, usb: 5, featUnlock: 1, spikeName: null, desc: "Mythic tier approaching. Ability score improvement. Unlock Level 16 feats." },
  { level: 17, campaignsNeeded: 66, usb: 6, featUnlock: 1, spikeName: null, desc: "USB +6. Legendary power." },
  { level: 18, campaignsNeeded: 75, usb: 6, featUnlock: 1, spikeName: "Final Spike", desc: "Endgame dominance. Unlock Level 18 feats." },
  { level: 19, campaignsNeeded: 85, usb: 6, featUnlock: 1, spikeName: null, desc: "Near ascension. Ability score improvement." },
  { level: 20, campaignsNeeded: 96, usb: 6, featUnlock: 1, spikeName: "Mythic Threshold", desc: "Legendary hero arc complete. Unlock Level 20 feats. Ascension available." },
];

export const LANGUAGES = [
  "Common",
  "Elvish",
  "Dwarvish",
  "Orcish",
  "Draconic",
  "Infernal",
  "Celestial",
  "Undercommon",
  "Sylvan",
  "Giant",
  "Gnomish",
  "Halfling",
  "Deep Speech",
  "Primordial",
  "Abyssal",
  "Druidic",
  "Thieves' Cant",
  "Ancient Greek",
  "Latin",
  "Norse Runic",
  "Egyptian Hieratic",
  "Sanskrit",
  "Sumerian",
  "Street Slang",
  "Corporate",
  "Net Code",
  "Binary",
  "Encrypted Signal",
  "Galactic Standard",
  "Xenian Chirp",
  "Hive Signal",
  "Machine Language",
  "Quantum Notation",
  "Spirit Tongue",
  "Dream Language",
  "Void Speech",
];

export function getModifier(score) {
  return Math.floor((score - 10) / 2);
}

export function formatMod(score) {
  const mod = getModifier(score);
  return mod >= 0 ? `+${mod}` : `${mod}`;
}

export function calculateHP(charClass, constitution, level) {
  const hitDieMap = { d6: 6, d8: 8, d10: 10, d12: 12 };
  const hitDie = hitDieMap[charClass?.hitDie] || 8;
  const conMod = getModifier(constitution || 10);
  return hitDie + conMod + (level - 1) * (Math.ceil(hitDie / 2) + conMod);
}

export function getUSB(level) {
  if (level <= 4) return 2;
  if (level <= 8) return 3;
  if (level <= 12) return 4;
  if (level <= 16) return 5;
  return 6;
}

export function getFeatsForLevel(level) {
  return FEATS.filter((f) => f.level <= level);
}

export function getLevelFromCampaigns(campaignsCompleted) {
  let level = 1;
  for (const tier of LEVEL_PROGRESSION) {
    if (campaignsCompleted >= tier.campaignsNeeded) {
      level = tier.level;
    }
  }
  return level;
}

export function isSpikeLevelReached(level) {
  const entry = LEVEL_PROGRESSION.find((l) => l.level === level);
  return entry?.spikeName || null;
}
