export const GENRES = [
  // ── DARK & HORROR ──
  {
    name: "Horror",
    description: "Dread, survival, the unknown",
    border: "border-red-900",
    color: "#8B2020",
    emoji: "🩸",
    tier: "R",
  },
  {
    name: "Lovecraftian",
    description: "Cosmic horror, forbidden knowledge",
    border: "border-red-950",
    color: "#6B1515",
    emoji: "🐙",
    tier: "R",
  },
  {
    name: "Cosmic Horror",
    description: "Reality is fragile, truth is unbearable",
    border: "border-red-900",
    color: "#7A1A1A",
    emoji: "🌌",
    tier: "R",
  },
  {
    name: "Zombie Apocalypse",
    description: "Undead threat, human conflict, hope",
    border: "border-red-800",
    color: "#8B2A2A",
    emoji: "🧟",
    tier: "R",
  },
  {
    name: "Gothic Romance",
    description: "Passion, tragedy, dark beauty",
    border: "border-purple-900",
    color: "#5B1A6B",
    emoji: "🌹",
    tier: "PG-13",
  },

  // ── SCI-FI & FUTURE ──
  {
    name: "Science Fiction",
    description: "Technology, exploration, humanity's future",
    border: "border-blue-700",
    color: "#1A4A8B",
    emoji: "🚀",
    tier: "PG",
  },
  {
    name: "Cyberpunk",
    description: "Neon dystopia, corporate power, hackers",
    border: "border-cyan-700",
    color: "#0E6B6B",
    emoji: "⚡",
    tier: "PG-13",
  },
  {
    name: "Space Opera",
    description: "Epic scale, galactic civilisations",
    border: "border-indigo-700",
    color: "#2A1A8B",
    emoji: "🌠",
    tier: "PG",
  },
  {
    name: "Biopunk",
    description: "Genetic engineering, body horror",
    border: "border-green-800",
    color: "#1A5B2A",
    emoji: "🧬",
    tier: "R",
  },
  {
    name: "Dieselpunk",
    description: "WWII-era grit with retrofuturistic tech",
    border: "border-yellow-800",
    color: "#6B4A0E",
    emoji: "⚙️",
    tier: "PG-13",
  },

  // ── FANTASY & MYTH ──
  {
    name: "Fantasy",
    description: "Magic, myth, heroic quests",
    border: "border-yellow-600",
    color: "#8B6A0E",
    emoji: "⚔️",
    tier: "PG",
  },
  {
    name: "Mythology & Legend",
    description: "Gods, heroes, divine intervention",
    border: "border-amber-600",
    color: "#8B5A0E",
    emoji: "🏛️",
    tier: "PG",
  },
  {
    name: "Steampunk",
    description: "Victorian tech, airships, clockwork wonder",
    border: "border-orange-700",
    color: "#8B3A0E",
    emoji: "🎩",
    tier: "PG",
  },
  {
    name: "Isekai / Portal Fantasy",
    description: "Stranger enters a new world",
    border: "border-pink-700",
    color: "#8B1A4A",
    emoji: "🌀",
    tier: "PG",
  },
  {
    name: "Solarpunk",
    description: "Hope, community, sustainable utopia",
    border: "border-green-600",
    color: "#1A6B2A",
    emoji: "🌱",
    tier: "G",
  },

  // ── CRIME & THRILLER ──
  {
    name: "Noir / Detective",
    description: "Moral ambiguity, crime, dark cities",
    border: "border-slate-600",
    color: "#2A3A4A",
    emoji: "🔍",
    tier: "PG-13",
  },
  {
    name: "Spy & Espionage",
    description: "Covert ops, double agents, global stakes",
    border: "border-slate-700",
    color: "#1A2A3A",
    emoji: "🕵️",
    tier: "PG-13",
  },
  {
    name: "Heist & Crime",
    description: "Planning, execution, betrayal",
    border: "border-gray-600",
    color: "#3A3A3A",
    emoji: "💎",
    tier: "PG-13",
  },
  {
    name: "Political Intrigue",
    description: "Power, betrayal, court politics",
    border: "border-slate-500",
    color: "#3A4A5A",
    emoji: "👑",
    tier: "PG",
  },
  {
    name: "Cozy Mystery",
    description: "Gentle intrigue, warm resolution",
    border: "border-amber-400",
    color: "#6B4A1A",
    emoji: "☕",
    tier: "G",
  },

  // ── ACTION & ADVENTURE ──
  {
    name: "Western",
    description: "Frontier, grit, freedom and consequence",
    border: "border-amber-700",
    color: "#8B5A1A",
    emoji: "🤠",
    tier: "PG-13",
  },
  {
    name: "Pirate / Age of Sail",
    description: "Freedom, treachery, the open sea",
    border: "border-blue-800",
    color: "#1A3A6B",
    emoji: "⚓",
    tier: "PG",
  },
  {
    name: "Superhero",
    description: "Powers, identity, responsibility",
    border: "border-red-600",
    color: "#6B1A1A",
    emoji: "🦸",
    tier: "PG",
  },
  {
    name: "Martial Arts / Wuxia",
    description: "Honour, mastery, spiritual power",
    border: "border-red-700",
    color: "#8B1A2A",
    emoji: "🥋",
    tier: "PG",
  },
  {
    name: "Military & War",
    description: "Camaraderie, sacrifice, the cost of conflict",
    border: "border-olive-700",
    color: "#3A4A1A",
    emoji: "🎖️",
    tier: "R",
  },

  // ── SURVIVAL & COLLAPSE ──
  {
    name: "Post-Apocalyptic",
    description: "Survival after collapse, reclaiming the world",
    border: "border-orange-800",
    color: "#8B3A1A",
    emoji: "☢️",
    tier: "PG-13",
  },
  {
    name: "Survival",
    description: "Resource scarcity, nature vs human",
    border: "border-green-700",
    color: "#1A4A1A",
    emoji: "🌲",
    tier: "PG-13",
  },
  {
    name: "Supernatural / Paranormal",
    description: "Ghosts, demons, the world behind the world",
    border: "border-violet-800",
    color: "#3A1A6B",
    emoji: "👻",
    tier: "PG-13",
  },

  // ── UNIQUE ──
  {
    name: "Time Travel",
    description: "Paradox, consequence, history as battlefield",
    border: "border-teal-700",
    color: "#0E4A4A",
    emoji: "⏳",
    tier: "PG",
  },
  {
    name: "Weird West",
    description: "Classic frontier meets monsters and magic",
    border: "border-amber-800",
    color: "#6B3A0E",
    emoji: "🌵",
    tier: "R",
  },
];

export const TIME_PERIODS = [
  {
    id: "deep_past",
    label: "Deep Past",
    desc: "Ancient — mythological ages, before recorded history",
  },
  {
    id: "historical_past",
    label: "Historical Past",
    desc: "Specific real-world era — Victorian, medieval, ancient Rome",
  },
  {
    id: "recent_past",
    label: "Recent Past",
    desc: "Within living memory — 1900s to 1990s",
  },
  {
    id: "present_day",
    label: "Present Day",
    desc: "Contemporary — right now",
  },
  {
    id: "near_future",
    label: "Near Future",
    desc: "10-100 years from now",
  },
  {
    id: "far_future",
    label: "Far Future",
    desc: "Centuries or millennia ahead",
  },
  {
    id: "alternate_history",
    label: "Alternate History",
    desc: "What if history took a different turn?",
  },
  {
    id: "timeless",
    label: "Timeless / Mythic",
    desc: "No fixed period — elemental, legendary, archetypal",
  },
];

export const PRESET_COMBOS = [
  {
    name: "Weird West",
    primary: "Horror",
    secondary: "Western",
    period: "historical_past",
    desc: "Monsters and magic on the Victorian frontier",
  },
  {
    name: "Shadowrun",
    primary: "Cyberpunk",
    secondary: "Fantasy",
    period: "near_future",
    desc: "Elves with guns, trolls in boardrooms, magic returned",
  },
  {
    name: "Deep Space Horror",
    primary: "Science Fiction",
    secondary: "Horror",
    period: "far_future",
    desc: "Something got aboard. Survival terror in space.",
  },
  {
    name: "Occult Detective",
    primary: "Noir / Detective",
    secondary: "Supernatural / Paranormal",
    period: "present_day",
    desc: "Hard-boiled investigator in a world where magic is real",
  },
  {
    name: "Magitek",
    primary: "Fantasy",
    secondary: "Science Fiction",
    period: "near_future",
    desc: "Magic and advanced technology coexist",
  },
  {
    name: "Firefly Run",
    primary: "Western",
    secondary: "Space Opera",
    period: "far_future",
    desc: "Frontier life on a distant colony world",
  },
  {
    name: "Chrome and Bone",
    primary: "Cyberpunk",
    secondary: "Horror",
    period: "near_future",
    desc: "When the implants start talking to you at 3am",
  },
  {
    name: "Iron Gods",
    primary: "Mythology & Legend",
    secondary: "Steampunk",
    period: "alternate_history",
    desc: "Ancient gods in an industrial revolution they didn't expect",
  },
];
